/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomBadge {
    }
}
declare global {
    interface HTMLCustomBadgeElement extends Components.CustomBadge, HTMLStencilElement {
    }
    var HTMLCustomBadgeElement: {
        prototype: HTMLCustomBadgeElement;
        new (): HTMLCustomBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "custom-badge": HTMLCustomBadgeElement;
    }
}
declare namespace LocalJSX {
    interface CustomBadge {
    }
    interface IntrinsicElements {
        "custom-badge": CustomBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-badge": LocalJSX.CustomBadge & JSXBase.HTMLAttributes<HTMLCustomBadgeElement>;
        }
    }
}
